# Generated by Django 4.0.4 on 2022-05-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
