# Generated by Django 4.0.4 on 2022-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pub_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sec_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='secret_pass',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
